### ISSUE TITLE
Too rigorous comparison

### ISSUE THREAD

**Issue by ALIENQuake** [BGforgeNet/msg2po#1]
The last improvements introduce reverting of perfectly fine translation:
https://github.com/InfinityMods/Ascension/commit/7066d0d9fa9a293f4cfd5bc2e41503e71aa6afe5#diff-8b634e7f30842ec1a6db8b9d46000f0a
The translation is fine, no one from Czech people complain so it cannot be simply reverted just because translation hasn't been verified from weblate interface by human.

**Comment by burner1024** [comment]
I do not think these translations are perfectly fine. It seems like an unfounded generalization to me.
Also, the very purpose of the system is to make human verification easy. If no one's doing it anyway, I don't see the reason to use it in the first place.

In any case, the previous behaviour was a bug, with fuzzy strings being extracted into resulting translation. I believe this is a greater evil, so it will stay fixed.

However, it's possible to add a flag to revert to the old behaviour, so that modders can use fuzzy translations in releases if they choose:
```
translation:
  extract_fuzzy: true
```
But don't come crying later if that bites you.

**Comment by burner1024** [comment]
I do not think these translations are perfectly fine. It seems like an unfounded generalization to me.
Also, the very purpose of the system is to make human verification easy. If no one's doing it anyway, I don't see the reason to use it in the first place.

In any case, the previous behaviour was a bug, with fuzzy strings being extracted into resulting translation. I believe this is a greater evil, so it will stay fixed.

However, it's possible to add a flag to revert to the old behaviour, so that modders can use fuzzy translations in releases if they choose:
```
translation:
  extract_fuzzy: true
```
But don't come crying later if that bites you.
